### ISSUE TITLE
Project dead?

### ISSUE THREAD

**Issue by dustinlacewell** [dannyfritz/flock-ecs#48]

**Comment by dannyfritz** [comment]
More or less yes. I'm actually on my 4th rewrite of it as of yesterday. I just can't get an API that I like within JavaScript.

**Comment by dustinlacewell** [comment]
What bits of the API are you most unhappy with?

**Comment by dannyfritz** [comment]
So I believe it is possibly an improvement over ECSY, but when using JavaScript objects I can never hit the performance I want. So I end up writing some implementations that use ArrayBuffers and end up having a really bad API, but super performant. Looking for some middle ground still; Some sort of Struct -> TypedArray API that has all or most of the JS Object/TS Interface ergonomics still.
